config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  resources :bbs

  root "top#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bb.rb
class Bb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bbs_controller.rb
class BbsController < ApplicationController
  before_action :set_bb, only: [:show, :edit, :update, :destroy]

  # GET /bbs
  # GET /bbs.json
  def index
    @bbs = Bb.all
  end

  # GET /bbs/1
  # GET /bbs/1.json
  def show
  end

  # GET /bbs/new
  def new
    @bb = Bb.new
  end

  # GET /bbs/1/edit
  def edit
  end

  # POST /bbs
  # POST /bbs.json
  def create
    @bb = Bb.new(bb_params)

    respond_to do |format|
      if @bb.save
        format.html { redirect_to @bb, notice: 'Bb was successfully created.' }
        format.json { render :show, status: :created, location: @bb }
      else
        format.html { render :new }
        format.json { render json: @bb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bbs/1
  # PATCH/PUT /bbs/1.json
  def update
    respond_to do |format|
      if @bb.update(bb_params)
        format.html { redirect_to @bb, notice: 'Bb was successfully updated.' }
        format.json { render :show, status: :ok, location: @bb }
      else
        format.html { render :edit }
        format.json { render json: @bb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bbs/1
  # DELETE /bbs/1.json
  def destroy
    @bb.destroy
    respond_to do |format|
      format.html { redirect_to bbs_url, notice: 'Bb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bb
      @bb = Bb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bb_params
      params.require(:bb).permit(:date, :title, :body)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbs_helper.rb
module BbsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/bbs/_form.html.erb
<%= form_with(model: bb, local: true) do |form| %>
  <% if bb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bb.errors.count, "error") %> prohibited this bb from being saved:</h2>

      <ul>
      <% bb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bbs/edit.html.erb
<h1>Editing Bb</h1>

<%= render 'form', bb: @bb %>

<%= link_to 'Show', @bb %> |
<%= link_to 'Back', bbs_path %>

app/views/bbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>掲示板（仮）</h1>

<CENTER>

<table>
  <thead>
    <tr>
      <th>登校日</th>
      <th>タイトル</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bbs.each do |bb| %>
      <tr>
        <td><%= bb.date %></td>
        <td><%= bb.title %></td>
        <td><%= bb.body %></td>
        <td><%= link_to '詳細', bb %></td>
        <td><%= link_to '編集', edit_bb_path(bb) %></td>
        <td><%= link_to '削除', bb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


</CENTER>
<br>

<%= link_to '新規投稿', new_bb_path %>
<%= link_to 'TOP', root_path %>

app/views/bbs/new.html.erb
<h1>New Bb</h1>

<%= render 'form', bb: @bb %>

<%= link_to 'Back', bbs_path %>

app/views/bbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @bb.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @bb.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @bb.body %>
</p>

<%= link_to 'Edit', edit_bb_path(@bb) %> |
<%= link_to 'Back', bbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog02</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>新宿掲示板</h1>
<p>ここをtop/indexとする。</p>
<br>
<img src="assets/001.jpeg" class="img-responsive">
<br>
<%= link_to '新規投稿', new_bb_path %>
<%= link_to '掲示板一覧', bbs_path %>